//! FR-5 (terrain_editor_overhaul_20260718): the Cities-Skylines-style terrain
//! tool palette. ui_shell_architecture Phase 4 folded the former floating
//! window into `ui_shell::right_sidebar::render_terrain_tools_section`; these
//! are now pure rendering helpers it calls directly (the Phase-2 reachability
//! toggle in `tool_panel.rs` was retired — the section rail is the sole
//! reveal path). Emits `UiAction::TerrainProposalAdd`/`TerrainProposalDelete`;
//! the true `TerrainHeightField`/tileset are never written here (NFR-1) — this
//! panel only ever builds action payloads. See `panels/AGENTS.md` §terrain-tools.

use bevy_egui::egui;

use crate::actions::terrain_proposal::SculptToolState;
use crate::actions::{UiAction, UiManager};
use crate::node_manager::curve;
use crate::panels::tool_panel::{TerrainToolMode, ToolPanelState};
use crate::terrain_proposal_state::ProposalEditState;
use crate::theme;

/// Default footprint radius (world units) seeded on first paint, mirroring
/// the Pen section's shape defaults in `tool_panel.rs`.
const DEFAULT_FOOTPRINT_RADIUS: f32 = 5.0;
/// Segment count for the circular footprint generated by "Add proposal".
const FOOTPRINT_SEGMENTS: usize = 24;

/// Seeds `terrain_footprint_radius` on first paint — idempotent, mirrors the
/// former window shell's lazy-seed exactly. Call once before rendering the
/// section body (see `right_sidebar::render_terrain_tools_section`).
pub(crate) fn ensure_defaults(tool_panel: &mut ToolPanelState) {
    if tool_panel.terrain_footprint_radius <= 0.0 {
        tool_panel.terrain_footprint_radius = DEFAULT_FOOTPRINT_RADIUS;
    }
}

/// The 8-button raise/lower/flatten/ramp/slope/pad/cut/fill mode picker.
pub(crate) fn render_palette(ui: &mut egui::Ui, tool_panel: &mut ToolPanelState) {
    ui.label(
        egui::RichText::new("Mode")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    egui::Grid::new("terrain_tool_mode_grid")
        .num_columns(4)
        .spacing([4.0, 4.0])
        .show(ui, |ui| {
            for (i, mode) in TerrainToolMode::ALL.into_iter().enumerate() {
                let active = tool_panel.terrain_tool_mode == mode;
                let btn = egui::Button::new(mode.label()).fill(if active {
                    theme::BG_BUTTON_ACTIVE
                } else {
                    theme::BG_BUTTON
                });
                if ui.add(btn).clicked() {
                    tool_panel.terrain_tool_mode = mode;
                }
                if (i + 1) % 4 == 0 {
                    ui.end_row();
                }
            }
        });
}

/// Footprint/height/delta control row + the "Add proposal" button that
/// builds `UiAction::TerrainProposalAdd`. Footprint is a circle centered at
/// the origin (same "append at origin, reposition later" convention as the
/// Pen section's shape buttons — see `tool_panel.rs::render_pen_section`);
/// dragging a placed proposal is a follow-up once FR-1/FR-3 gimbal-on-typed-
/// selection wiring lands elsewhere in this track.
pub(crate) fn render_controls_and_emit(
    ui: &mut egui::Ui,
    tool_panel: &mut ToolPanelState,
    ui_mgr: &mut UiManager,
) {
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Footprint radius")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(
            egui::DragValue::new(&mut tool_panel.terrain_footprint_radius)
                .speed(0.1)
                .range(0.1..=f32::MAX)
                .suffix(" wu"),
        );
    });
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Target height")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::DragValue::new(&mut tool_panel.terrain_target_height).speed(0.1));
    });
    ui.horizontal(|ui| {
        ui.label(egui::RichText::new("Delta").small().color(theme::TEXT_DIM));
        ui.add(egui::DragValue::new(&mut tool_panel.terrain_delta).speed(0.1));
    });
    ui.add_space(4.0);

    if ui
        .button(format!(
            "Add {} proposal",
            tool_panel.terrain_tool_mode.label()
        ))
        .on_hover_text("Adds a non-destructive proposed overlay — true terrain is never written")
        .clicked()
    {
        // curve::circle emits XZ-plane [x, y, z] points (y = 0); the proposal
        // footprint is 2-D [x, z] to match the JSON contract + fe_terrain.
        let footprint: Vec<[f32; 2]> = curve::circle(
            [0.0, 0.0, 0.0],
            tool_panel.terrain_footprint_radius,
            FOOTPRINT_SEGMENTS,
        )
        .into_iter()
        .map(|[x, _, z]| [x, z])
        .collect();
        ui_mgr.push_action(UiAction::TerrainProposalAdd {
            op: tool_panel.terrain_tool_mode.to_proposal_op(),
            footprint,
            target_height: Some(tool_panel.terrain_target_height),
            delta: Some(tool_panel.terrain_delta),
        });
    }
    ui.label(
        egui::RichText::new(
            "Proposals append at the origin; drag to reposition once gimbal-on-proposal lands.",
        )
        .small()
        .color(theme::TEXT_MUTED)
        .italics(),
    );
}

/// Select/delete list of existing proposals. Selecting sets
/// `ProposalEditState.selected`, read by `proposal_report_panel`.
pub(crate) fn render_proposal_list(
    ui: &mut egui::Ui,
    proposal_state: &mut ProposalEditState,
    ui_mgr: &mut UiManager,
) {
    ui.label(
        egui::RichText::new("Proposals")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    if proposal_state.proposals.is_empty() {
        ui.label(
            egui::RichText::new("No proposals yet.")
                .small()
                .color(theme::TEXT_MUTED)
                .italics(),
        );
        return;
    }

    // Collect an owned display list first (id, debug label) so the loop below
    // holds no live borrow of `proposal_state.proposals` — lets it freely
    // write `proposal_state.selected` without a disjoint-field-borrow
    // question across the `ui.horizontal` closure boundary.
    let rows: Vec<(String, String)> = proposal_state
        .proposals
        .iter()
        .map(|r| (r.id.clone(), format!("{:?}", r.op)))
        .collect();

    let mut delete_id: Option<String> = None;
    egui::ScrollArea::vertical()
        .auto_shrink([false, true])
        .max_height(160.0)
        .show(ui, |ui| {
            for (id, label) in &rows {
                ui.horizontal(|ui| {
                    let selected = proposal_state.selected.as_deref() == Some(id.as_str());
                    if ui.selectable_label(selected, label.as_str()).clicked() {
                        proposal_state.selected = Some(id.clone());
                    }
                    if ui
                        .small_button("\u{2715}")
                        .on_hover_text("Delete proposal")
                        .clicked()
                    {
                        delete_id = Some(id.clone());
                    }
                });
            }
        });

    if let Some(id) = delete_id {
        if proposal_state.selected.as_deref() == Some(id.as_str()) {
            proposal_state.selected = None;
        }
        ui_mgr.push_action(UiAction::TerrainProposalDelete { id });
    }
}

/// Wave-1 seam (T3 sculpt_earthwork_regions): T3's brush/shape sculpt UI folds
/// in here (reads/writes `SculptToolState`); calm "Sculpt tools — Wave 1" hint
/// until then (ui_ux §7). `_sculpt_state` is the threaded seam T3 un-underscores
/// and fills — same stub idiom as `actions/terrain_proposal.rs` (T3 owns fields).
pub(crate) fn render_sculpt_placeholder(ui: &mut egui::Ui, _sculpt_state: &mut SculptToolState) {
    ui.label(
        egui::RichText::new("Sculpt")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    ui.label(
        egui::RichText::new("Sculpt tools — Wave 1")
            .small()
            .color(theme::TEXT_MUTED)
            .italics(),
    );
}
