//! FR-5 (terrain_editor_overhaul_20260718): the Cities-Skylines-style terrain
//! tool palette. ui_shell_architecture Phase 4 folded the former floating
//! window into `ui_shell::right_sidebar::render_terrain_tools_section`; these
//! are now pure rendering helpers it calls directly (the Phase-2 reachability
//! toggle in `tool_panel.rs` was retired — the section rail is the sole
//! reveal path). Emits `UiAction::TerrainProposalAdd`/`TerrainProposalDelete`;
//! the true `TerrainHeightField`/tileset are never written here (NFR-1) — this
//! panel only ever builds action payloads. See `panels/AGENTS.md` §terrain-tools.

use bevy_egui::egui;

use crate::actions::terrain_proposal::{SculptOpKind, SculptShapeMode, SculptToolState};
use crate::actions::{UiAction, UiManager};
use crate::node_manager::curve;
use crate::panels::tool_panel::{TerrainToolMode, ToolPanelState};
use crate::terrain_proposal_state::ProposalEditState;
use crate::theme;

/// Default footprint radius (world units) seeded on first paint, mirroring
/// the Pen section's shape defaults in `tool_panel.rs`.
const DEFAULT_FOOTPRINT_RADIUS: f32 = 5.0;
/// Segment count for the circular footprint generated by "Add proposal".
const FOOTPRINT_SEGMENTS: usize = 24;

/// Seeds `terrain_footprint_radius` on first paint — idempotent, mirrors the
/// former window shell's lazy-seed exactly. Call once before rendering the
/// section body (see `right_sidebar::render_terrain_tools_section`).
pub(crate) fn ensure_defaults(tool_panel: &mut ToolPanelState) {
    if tool_panel.terrain_footprint_radius <= 0.0 {
        tool_panel.terrain_footprint_radius = DEFAULT_FOOTPRINT_RADIUS;
    }
}

/// The 8-button raise/lower/flatten/ramp/slope/pad/cut/fill mode picker.
pub(crate) fn render_palette(ui: &mut egui::Ui, tool_panel: &mut ToolPanelState) {
    ui.label(
        egui::RichText::new("Mode")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    egui::Grid::new("terrain_tool_mode_grid")
        .num_columns(4)
        .spacing([4.0, 4.0])
        .show(ui, |ui| {
            for (i, mode) in TerrainToolMode::ALL.into_iter().enumerate() {
                let active = tool_panel.terrain_tool_mode == mode;
                let btn = egui::Button::new(mode.label()).fill(if active {
                    theme::BG_BUTTON_ACTIVE
                } else {
                    theme::BG_BUTTON
                });
                if ui.add(btn).clicked() {
                    tool_panel.terrain_tool_mode = mode;
                }
                if (i + 1) % 4 == 0 {
                    ui.end_row();
                }
            }
        });
}

/// Footprint/height/delta control row + the "Add proposal" button that
/// builds `UiAction::TerrainProposalAdd`. Footprint is a circle centered at
/// the origin (same "append at origin, reposition later" convention as the
/// Pen section's shape buttons — see `tool_panel.rs::render_pen_section`);
/// dragging a placed proposal is a follow-up once FR-1/FR-3 gimbal-on-typed-
/// selection wiring lands elsewhere in this track.
pub(crate) fn render_controls_and_emit(
    ui: &mut egui::Ui,
    tool_panel: &mut ToolPanelState,
    ui_mgr: &mut UiManager,
) {
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Footprint radius")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(
            egui::DragValue::new(&mut tool_panel.terrain_footprint_radius)
                .speed(0.1)
                .range(0.1..=f32::MAX)
                .suffix(" wu"),
        );
    });
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Target height")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::DragValue::new(&mut tool_panel.terrain_target_height).speed(0.1));
    });
    ui.horizontal(|ui| {
        ui.label(egui::RichText::new("Delta").small().color(theme::TEXT_DIM));
        ui.add(egui::DragValue::new(&mut tool_panel.terrain_delta).speed(0.1));
    });
    ui.add_space(4.0);

    if ui
        .button(format!(
            "Add {} proposal",
            tool_panel.terrain_tool_mode.label()
        ))
        .on_hover_text("Adds a non-destructive proposed overlay — true terrain is never written")
        .clicked()
    {
        // curve::circle emits XZ-plane [x, y, z] points (y = 0); the proposal
        // footprint is 2-D [x, z] to match the JSON contract + fe_terrain.
        let footprint: Vec<[f32; 2]> = curve::circle(
            [0.0, 0.0, 0.0],
            tool_panel.terrain_footprint_radius,
            FOOTPRINT_SEGMENTS,
        )
        .into_iter()
        .map(|[x, _, z]| [x, z])
        .collect();
        ui_mgr.push_action(UiAction::TerrainProposalAdd {
            op: tool_panel.terrain_tool_mode.to_proposal_op(),
            footprint,
            target_height: Some(tool_panel.terrain_target_height),
            delta: Some(tool_panel.terrain_delta),
        });
    }
    ui.label(
        egui::RichText::new(
            "Proposals append at the origin; drag to reposition once gimbal-on-proposal lands.",
        )
        .small()
        .color(theme::TEXT_MUTED)
        .italics(),
    );
}

/// Select/delete list of existing proposals. Selecting sets
/// `ProposalEditState.selected`, read by `proposal_report_panel`.
pub(crate) fn render_proposal_list(
    ui: &mut egui::Ui,
    proposal_state: &mut ProposalEditState,
    ui_mgr: &mut UiManager,
) {
    ui.label(
        egui::RichText::new("Proposals")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    if proposal_state.proposals.is_empty() {
        ui.label(
            egui::RichText::new("No proposals yet.")
                .small()
                .color(theme::TEXT_MUTED)
                .italics(),
        );
        return;
    }

    // Collect an owned display list first (id, debug label) so the loop below
    // holds no live borrow of `proposal_state.proposals` — lets it freely
    // write `proposal_state.selected` without a disjoint-field-borrow
    // question across the `ui.horizontal` closure boundary.
    let rows: Vec<(String, String)> = proposal_state
        .proposals
        .iter()
        .map(|r| (r.id.clone(), format!("{:?}", r.op)))
        .collect();

    let mut delete_id: Option<String> = None;
    egui::ScrollArea::vertical()
        .auto_shrink([false, true])
        .max_height(160.0)
        .show(ui, |ui| {
            for (id, label) in &rows {
                ui.horizontal(|ui| {
                    let selected = proposal_state.selected.as_deref() == Some(id.as_str());
                    if ui.selectable_label(selected, label.as_str()).clicked() {
                        proposal_state.selected = Some(id.clone());
                    }
                    if ui
                        .small_button("\u{2715}")
                        .on_hover_text("Delete proposal")
                        .clicked()
                    {
                        delete_id = Some(id.clone());
                    }
                });
            }
        });

    if let Some(id) = delete_id {
        if proposal_state.selected.as_deref() == Some(id.as_str()) {
            proposal_state.selected = None;
        }
        ui_mgr.push_action(UiAction::TerrainProposalDelete { id });
    }
}

/// Planar area (scene units²) of the armed sculpt footprint — πr² for a
/// disc/circle, w×h for a rect, shoelace for the polygon draft. Pure so the
/// sculpt section's live readout is unit-testable. Unscaled (the panel has no
/// `world_scale`); the real-unit metric lives in the Proposal report (FR-5).
pub(crate) fn sculpt_footprint_area(sculpt: &SculptToolState) -> f32 {
    match sculpt.shape_mode {
        SculptShapeMode::Brush | SculptShapeMode::Circle => {
            std::f32::consts::PI * sculpt.radius * sculpt.radius
        }
        SculptShapeMode::Rect => {
            // A Radius×Radius square centred on the origin (2r on a side).
            (2.0 * sculpt.radius) * (2.0 * sculpt.radius)
        }
        SculptShapeMode::Polygon => {
            let p = &sculpt.region_draft;
            if p.len() < 3 {
                return 0.0;
            }
            let mut sum = 0.0f32;
            for i in 0..p.len() {
                let [x1, z1] = p[i];
                let [x2, z2] = p[(i + 1) % p.len()];
                sum += x1 * z2 - x2 * z1;
            }
            sum.abs() * 0.5
        }
    }
}

/// T3 FR-1/FR-2 sculpt section (folded into TerrainTools — no new
/// `RightSidebarSection`). Configures `SculptToolState` (shape mode, op, brush
/// radius/strength, level target + delta, material, polygon draft) — the tactile
/// area-selection controls (D-A8). NOTE the frozen scaffold seam: this fn has no
/// `ui_mgr`/petal handle, so the actual brush-paint + defined-shape REGION
/// COMMIT is viewport/interaction-driven (emits `UiAction::Sculpt*` once T6
/// threads the active petal + drains `SculptToolState.pending_actions`, mirroring
/// `ToolPanelState.drain_pending`). Region CREATE/DELETE + reporting work today
/// through the evolved proposal path above (FR-6). See `panels/AGENTS.md`
/// §terrain-tools. Kept named `render_sculpt_placeholder` (T6's frozen call site).
pub(crate) fn render_sculpt_placeholder(ui: &mut egui::Ui, sculpt_state: &mut SculptToolState) {
    ui.label(
        egui::RichText::new("Sculpt")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);

    // Shape mode — brush (tactile) vs defined circle/rect/polygon (reportable).
    ui.label(egui::RichText::new("Shape").small().color(theme::TEXT_DIM));
    ui.horizontal_wrapped(|ui| {
        for mode in SculptShapeMode::ALL {
            ui.selectable_value(&mut sculpt_state.shape_mode, mode, mode.label());
        }
    });
    ui.add_space(4.0);

    // Sculpt operation.
    ui.label(
        egui::RichText::new("Operation")
            .small()
            .color(theme::TEXT_DIM),
    );
    ui.horizontal_wrapped(|ui| {
        for op in SculptOpKind::ALL {
            ui.selectable_value(&mut sculpt_state.op, op, op.label());
        }
    });
    ui.add_space(4.0);

    ui.horizontal(|ui| {
        ui.label(egui::RichText::new("Radius").small().color(theme::TEXT_DIM));
        ui.add(
            egui::DragValue::new(&mut sculpt_state.radius)
                .speed(0.1)
                .range(0.1..=f32::MAX)
                .suffix(" m"),
        );
    });
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Strength")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::Slider::new(&mut sculpt_state.strength, 0.0..=1.0).show_value(true));
    });

    // Op-specific magnitude control.
    match sculpt_state.op {
        SculptOpKind::Level => {
            ui.horizontal(|ui| {
                ui.label(
                    egui::RichText::new("Target height")
                        .small()
                        .color(theme::TEXT_DIM),
                );
                ui.add(egui::DragValue::new(&mut sculpt_state.target_height).speed(0.1));
            });
        }
        SculptOpKind::Raise | SculptOpKind::Lower => {
            ui.horizontal(|ui| {
                ui.label(egui::RichText::new("Delta").small().color(theme::TEXT_DIM));
                ui.add(egui::DragValue::new(&mut sculpt_state.delta).speed(0.1));
            });
        }
        SculptOpKind::Smooth => {
            ui.label(
                egui::RichText::new("Smooth relaxes toward the region's mean height.")
                    .small()
                    .color(theme::TEXT_MUTED)
                    .italics(),
            );
        }
    }
    ui.add_space(4.0);

    // Material tag (single-material this landing, Q-3) — baked into the region.
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Material")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::TextEdit::singleline(&mut sculpt_state.material).desired_width(120.0));
    });
    ui.add_space(4.0);

    // Polygon draft management (defined-polygon footprints are painted in the
    // viewport; the panel shows/clears the in-progress draft).
    if sculpt_state.shape_mode == SculptShapeMode::Polygon {
        ui.horizontal(|ui| {
            ui.label(
                egui::RichText::new(format!(
                    "Polygon draft: {} point(s)",
                    sculpt_state.region_draft.len()
                ))
                .small()
                .color(theme::TEXT_DIM),
            );
            if ui.small_button("Clear").clicked() {
                sculpt_state.region_draft.clear();
            }
        });
        ui.add_space(4.0);
    }

    // Live footprint area readout (scene units; the real-unit cut/fill is in the
    // Proposal report — FR-5).
    let area = sculpt_footprint_area(sculpt_state);
    ui.label(
        egui::RichText::new(format!("Footprint area \u{2248} {area:.1} u\u{b2}"))
            .small()
            .color(theme::TEXT_MUTED),
    );
    ui.add_space(2.0);
    ui.label(
        egui::RichText::new(
            "Paint the region in the viewport to commit; cut/fill volume shows in the Proposal report.",
        )
        .small()
        .color(theme::TEXT_MUTED)
        .italics(),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sculpt_area_disc_rect_and_polygon() {
        // Circle: πr².
        let circle = SculptToolState {
            shape_mode: SculptShapeMode::Circle,
            radius: 2.0,
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&circle) - std::f32::consts::PI * 4.0).abs() < 1e-3);
        // Rect: a 2r-per-side square → (2r)².
        let rect = SculptToolState {
            shape_mode: SculptShapeMode::Rect,
            radius: 3.0,
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&rect) - 36.0).abs() < 1e-3);
        // Polygon: a 10×10 square draft → area 100; <3 points → 0.
        let poly = SculptToolState {
            shape_mode: SculptShapeMode::Polygon,
            region_draft: vec![[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0]],
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&poly) - 100.0).abs() < 1e-3);
        let empty = SculptToolState {
            shape_mode: SculptShapeMode::Polygon,
            region_draft: vec![[0.0, 0.0], [1.0, 0.0]],
            ..Default::default()
        };
        assert_eq!(sculpt_footprint_area(&empty), 0.0);
    }
}
