//! FR-5 (terrain_editor_overhaul_20260718): the Cities-Skylines-style terrain
//! tool palette. ui_shell_architecture Phase 4 folded the former floating
//! window into `ui_shell::right_sidebar::render_terrain_tools_section`; these
//! are now pure rendering helpers it calls directly (the section rail is the
//! sole reveal path, plus `UiAction::RevealSection { slug: "terrain" }` from
//! the Brush options cross-link). Emits
//! `UiAction::TerrainProposalAdd`/`TerrainProposalDelete`; the true
//! `TerrainHeightField`/tileset are never written here (NFR-1) — this panel
//! only ever builds action payloads. As of D6-B the TerrainTools section holds
//! ONLY the proposal palette/controls/list: `render_brush_controls` and
//! `sculpt_footprint_area` are called from the Options section's Brush arm
//! (`panels::tool_options`), which also calls `circle_footprint`/
//! `rect_footprint` to wire the shape-mode Apply affordance (finding #14).
//! Phase 6 (D17, finding #9): `render_controls_and_emit` now takes the
//! caller's `world_scale` (`PetalMapState.world_scale`) so the footprint
//! radius/target height/delta fields display and edit in real metres instead
//! of unlabeled world units — see its doc comment for the exact boundary.
//! See `panels/AGENTS.md` §terrain-tools.

use bevy_egui::egui;

use crate::actions::terrain_proposal::MAX_SCULPT_DISTANCE;
use crate::actions::terrain_proposal::{SculptOpKind, SculptShapeMode, SculptToolState};
use crate::actions::{UiAction, UiManager};
use crate::geometry::{meters_to_world, world_to_meters};
use crate::node_manager::curve;
use crate::panels::tool_panel::{TerrainToolMode, ToolPanelState};
use crate::terrain_proposal_state::ProposalEditState;
use crate::theme;

/// D12-A ratified disclosure copy (finding #2): the 8-mode palette's
/// proposals have no material/bake path (`fe-terrain/src/terrain_proposal.rs`
/// requires `material` and hard-rejects `Flatten|Ramp|Slope|Pad|Cut|Fill`), so
/// every mode's surface says so at rest — not just on hover. Shown in both
/// `render_palette` and `render_controls_and_emit` (identical wording, one
/// source, so the two copies can't drift).
pub(crate) const PROPOSAL_ONLY_DISCLOSURE: &str = "Proposal only — does not modify terrain.";

/// Segment count for the circular footprint generated by "Add proposal".
const FOOTPRINT_SEGMENTS: usize = 24;

/// Seeds `terrain_footprint_radius` on first paint — idempotent, mirrors the
/// former window shell's lazy-seed exactly. Call once before rendering the
/// section body (see `right_sidebar::render_terrain_tools_section`).
pub(crate) fn ensure_defaults(tool_panel: &mut ToolPanelState) {
    tool_panel.sanitize_numeric_state();
}

/// The 8-button raise/lower/flatten/ramp/slope/pad/cut/fill mode picker.
pub(crate) fn render_palette(ui: &mut egui::Ui, tool_panel: &mut ToolPanelState) {
    ui.label(
        egui::RichText::new("Mode")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    egui::Grid::new("terrain_tool_mode_grid")
        .num_columns(4)
        .spacing([4.0, 4.0])
        .show(ui, |ui| {
            for (i, mode) in TerrainToolMode::ALL.into_iter().enumerate() {
                let active = tool_panel.terrain_tool_mode == mode;
                let btn = egui::Button::new(mode.label()).fill(if active {
                    theme::BG_BUTTON_ACTIVE
                } else {
                    theme::BG_BUTTON
                });
                if ui.add(btn).clicked() {
                    tool_panel.terrain_tool_mode = mode;
                }
                if (i + 1) % 4 == 0 {
                    ui.end_row();
                }
            }
        });
    ui.add_space(4.0);
    ui.label(
        egui::RichText::new(PROPOSAL_ONLY_DISCLOSURE)
            .small()
            .color(theme::TEXT_MUTED)
            .italics(),
    );
}

/// Whether `world_scale` is a real, usable map scale (NFR-4) — mirrors
/// `geometry::sanitize_world_scale`'s finite-and-positive gate and
/// `proposal_report_panel::compute_report`'s `has_scale`. Pure.
pub(crate) fn has_real_scale(world_scale: f64) -> bool {
    world_scale.is_finite() && world_scale > 0.0
}

/// DragValue suffix for the footprint radius/target height/delta fields:
/// real meters when the petal has a usable map scale, raw world units when
/// it does not — NEVER a fake meters label (D17, finding #9). Pure.
fn distance_unit_suffix(world_scale: f64) -> &'static str {
    if has_real_scale(world_scale) {
        " m"
    } else {
        " world units"
    }
}

/// The world_scale chip's text. The unset-scale wording is byte-identical to
/// `proposal_report_panel`'s NFR-4 chip (`"no map scale — showing world
/// units"`) so the two surfaces never say the same thing two different ways.
/// Pure.
fn scale_chip_text(world_scale: f64) -> String {
    if has_real_scale(world_scale) {
        format!("Map scale: {world_scale:.4} world units per meter")
    } else {
        "no map scale — showing world units".to_string()
    }
}

fn render_world_scale_chip(ui: &mut egui::Ui, world_scale: f64) {
    ui.label(
        egui::RichText::new(scale_chip_text(world_scale))
            .small()
            .color(theme::TEXT_MUTED)
            .italics(),
    );
}

/// Footprint/height/delta control row + the "Add proposal" button that
/// builds `UiAction::TerrainProposalAdd`. Footprint is a circle centered at
/// the origin (same "append at origin, reposition later" convention as the
/// Pen section's shape buttons — see `tool_panel.rs::render_pen_section`);
/// dragging a placed proposal is a follow-up once FR-1/FR-3 gimbal-on-typed-
/// selection wiring lands elsewhere in this track.
///
/// D17 (finding #9): `ToolPanelState.terrain_footprint_radius/
/// terrain_target_height/terrain_delta` stay stored in WORLD UNITS (still fed
/// straight into `curve::circle`/`TerrainProposalAdd` below, unchanged) — only
/// the DragValue *display and entry* converts through `world_to_meters`/
/// `meters_to_world` at the widget boundary, matching the sibling Brush
/// controls one scroll away which are meters-native in `SculptToolState`.
/// `world_scale` must come from the caller (`PetalMapState.world_scale`,
/// threaded via `right_sidebar::render_terrain_tools_section`).
pub(crate) fn render_controls_and_emit(
    ui: &mut egui::Ui,
    tool_panel: &mut ToolPanelState,
    ui_mgr: &mut UiManager,
    world_scale: f64,
) {
    tool_panel.sanitize_numeric_state();
    render_world_scale_chip(ui, world_scale);
    ui.add_space(2.0);
    let unit_suffix = distance_unit_suffix(world_scale);
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Footprint radius")
                .small()
                .color(theme::TEXT_DIM),
        );
        let mut radius_display = world_to_meters(tool_panel.terrain_footprint_radius, world_scale);
        // F8 fix (`ui_semantics_unification_20260808`): egui's DragValue
        // clamps an out-of-range value to `.range(...)` on its very FIRST
        // paint, calling `mark_changed()` even without user interaction.
        // Because `radius_display` is a per-frame conversion of the stored
        // WORLD-UNIT value through `world_to_meters`, a petal with a large
        // `world_scale` can produce a meters value outside this widget's
        // range purely from the conversion — clamping it would then write a
        // corrupted value back through `meters_to_world` below merely from
        // OPENING this section, never from a drag. `false` keeps the drag
        // RANGE (dragging still clamps) without rewriting an existing value.
        let resp = ui.add(
            egui::DragValue::new(&mut radius_display)
                .speed(0.1)
                .range(0.1..=MAX_SCULPT_DISTANCE)
                .clamp_existing_to_range(false)
                .suffix(unit_suffix),
        );
        if resp.changed() {
            tool_panel.terrain_footprint_radius = meters_to_world(radius_display, world_scale);
        }
    });
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Target height")
                .small()
                .color(theme::TEXT_DIM),
        );
        let mut height_display = world_to_meters(tool_panel.terrain_target_height, world_scale);
        // F8 fix — see the Footprint radius widget above for why.
        let resp = ui.add(
            egui::DragValue::new(&mut height_display)
                .speed(0.1)
                .range(-MAX_SCULPT_DISTANCE..=MAX_SCULPT_DISTANCE)
                .clamp_existing_to_range(false)
                .suffix(unit_suffix),
        );
        if resp.changed() {
            tool_panel.terrain_target_height = meters_to_world(height_display, world_scale);
        }
    });
    ui.horizontal(|ui| {
        ui.label(egui::RichText::new("Delta").small().color(theme::TEXT_DIM));
        let mut delta_display = world_to_meters(tool_panel.terrain_delta, world_scale);
        // F8 fix — see the Footprint radius widget above for why.
        let resp = ui.add(
            egui::DragValue::new(&mut delta_display)
                .speed(0.1)
                .range(-MAX_SCULPT_DISTANCE..=MAX_SCULPT_DISTANCE)
                .clamp_existing_to_range(false)
                .suffix(unit_suffix),
        );
        if resp.changed() {
            tool_panel.terrain_delta = meters_to_world(delta_display, world_scale);
        }
    });
    ui.add_space(4.0);

    if ui
        .button(format!(
            "Add {} proposal",
            tool_panel.terrain_tool_mode.label()
        ))
        .on_hover_text(PROPOSAL_ONLY_DISCLOSURE)
        .clicked()
    {
        // curve::circle emits XZ-plane [x, y, z] points (y = 0); the proposal
        // footprint is 2-D [x, z] to match the JSON contract + fe_terrain.
        // Still world units — the metres conversion above is display-only.
        let footprint: Vec<[f32; 2]> = curve::circle(
            [0.0, 0.0, 0.0],
            tool_panel.terrain_footprint_radius,
            FOOTPRINT_SEGMENTS,
        )
        .into_iter()
        .map(|[x, _, z]| [x, z])
        .collect();
        ui_mgr.push_action(UiAction::TerrainProposalAdd {
            op: tool_panel.terrain_tool_mode.to_proposal_op(),
            footprint,
            target_height: Some(tool_panel.terrain_target_height),
            delta: Some(tool_panel.terrain_delta),
        });
    }
    ui.label(
        egui::RichText::new(
            "Proposals append at the origin; drag to reposition once gimbal-on-proposal lands.",
        )
        .small()
        .color(theme::TEXT_MUTED)
        .italics(),
    );
    ui.add_space(2.0);
    ui.label(
        egui::RichText::new(PROPOSAL_ONLY_DISCLOSURE)
            .small()
            .color(theme::TEXT_MUTED)
            .italics(),
    );
}

/// Select/delete list of existing proposals. Selecting sets
/// `ProposalEditState.selected`, read by `proposal_report_panel`.
pub(crate) fn render_proposal_list(
    ui: &mut egui::Ui,
    proposal_state: &mut ProposalEditState,
    ui_mgr: &mut UiManager,
) {
    ui.label(
        egui::RichText::new("Proposals")
            .strong()
            .color(theme::TEXT_SECTION),
    );
    ui.add_space(2.0);
    if proposal_state.proposals.is_empty() {
        ui.label(
            egui::RichText::new("No proposals yet.")
                .small()
                .color(theme::TEXT_MUTED)
                .italics(),
        );
        return;
    }

    // Collect an owned display list first (id, debug label) so the loop below
    // holds no live borrow of `proposal_state.proposals` — lets it freely
    // write `proposal_state.selected` without a disjoint-field-borrow
    // question across the `ui.horizontal` closure boundary.
    let rows: Vec<(String, String)> = proposal_state
        .proposals
        .iter()
        .map(|r| (r.id.clone(), format!("{:?}", r.op)))
        .collect();

    let mut delete_id: Option<String> = None;
    egui::ScrollArea::vertical()
        .auto_shrink([false, true])
        .max_height(160.0)
        .show(ui, |ui| {
            for (id, label) in &rows {
                ui.horizontal(|ui| {
                    let selected = proposal_state.selected.as_deref() == Some(id.as_str());
                    if ui.selectable_label(selected, label.as_str()).clicked() {
                        proposal_state.selected = Some(id.clone());
                    }
                    if ui
                        .small_button("\u{2715}")
                        .on_hover_text("Delete proposal")
                        .clicked()
                    {
                        delete_id = Some(id.clone());
                    }
                });
            }
        });

    if let Some(id) = delete_id {
        if proposal_state.selected.as_deref() == Some(id.as_str()) {
            proposal_state.selected = None;
        }
        ui_mgr.push_action(UiAction::TerrainProposalDelete { id });
    }
}

/// Planar area (scene units²) of the armed sculpt footprint — πr² for a
/// disc/circle, w×h for a rect, shoelace for the polygon draft. Pure so the
/// readout is unit-testable. Unscaled (the panel has no `world_scale`); the
/// real-unit metric lives in the Proposal report (FR-5). Rendered by the Brush
/// arm of the Options section since D6-B.
pub(crate) fn sculpt_footprint_area(sculpt: &SculptToolState) -> f32 {
    match sculpt.shape_mode {
        SculptShapeMode::Brush | SculptShapeMode::Circle => {
            std::f32::consts::PI * sculpt.radius * sculpt.radius
        }
        SculptShapeMode::Rect => {
            // A Radius×Radius square centred on the origin (2r on a side).
            (2.0 * sculpt.radius) * (2.0 * sculpt.radius)
        }
        SculptShapeMode::Polygon => {
            let p = &sculpt.region_draft;
            if p.len() < 3 {
                return 0.0;
            }
            let mut sum = 0.0f32;
            for i in 0..p.len() {
                let [x1, z1] = p[i];
                let [x2, z2] = p[(i + 1) % p.len()];
                sum += x1 * z2 - x2 * z1;
            }
            sum.abs() * 0.5
        }
    }
}

/// Defined-circle footprint for the sculpt shape picker's Circle apply
/// affordance (finding #14, wired in `panels::tool_options`) — same segment
/// count and origin-anchored convention as the palette's circle above, and
/// the same units as `SculptToolState.radius` (petal-local meters, N-1):
/// `SculptShapeRegion`'s footprint stays meters, unlike the freeform Brush
/// stroke's world-unit snapshot (`brush_interaction::BrushSnapshot`). Pure.
pub(crate) fn circle_footprint(radius: f32) -> Vec<[f32; 2]> {
    curve::circle([0.0, 0.0, 0.0], radius, FOOTPRINT_SEGMENTS)
        .into_iter()
        .map(|[x, _, z]| [x, z])
        .collect()
}

/// Defined-rectangle footprint for the Rect apply affordance: a
/// `2×radius`-per-side axis-aligned square centred on the origin — mirrors
/// `sculpt_footprint_area`'s Rect case exactly. Pure.
pub(crate) fn rect_footprint(radius: f32) -> Vec<[f32; 2]> {
    vec![
        [-radius, -radius],
        [radius, -radius],
        [radius, radius],
        [-radius, radius],
    ]
}

/// T3 FR-1/FR-2 sculpt controls — THE single copy (D6-B). The near-duplicate
/// `render_sculpt_placeholder` that used to sit permanently in the TerrainTools
/// section is DELETED (finding #7: same `SculptToolState`, two hosts, different
/// widget sets, no UI signal they were linked); its shape-mode picker, polygon
/// draft and footprint readout moved to the Brush arm of the Options section
/// (`panels::tool_options`), which now calls this fn as the tool's only
/// settings surface. Viewport Brush interaction still owns commits.
pub(crate) fn render_brush_controls(ui: &mut egui::Ui, sculpt: &mut SculptToolState) {
    sculpt.sanitize_numeric_state();
    ui.label(
        egui::RichText::new("BRUSH")
            .small()
            .color(theme::TEXT_SECTION),
    );
    ui.horizontal(|ui| {
        ui.label(egui::RichText::new("Radius").small().color(theme::TEXT_DIM));
        ui.add(
            egui::DragValue::new(&mut sculpt.radius)
                .speed(0.1)
                .range(0.1..=MAX_SCULPT_DISTANCE)
                .suffix(" m"),
        );
    });
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Strength")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::Slider::new(&mut sculpt.strength, 0.0..=1.0));
    });
    ui.label(
        egui::RichText::new("Operation")
            .small()
            .color(theme::TEXT_DIM),
    );
    ui.horizontal_wrapped(|ui| {
        for op in SculptOpKind::ALL {
            ui.selectable_value(&mut sculpt.op, op, op.label());
        }
    });
    match sculpt.op {
        SculptOpKind::Level => {
            ui.horizontal(|ui| {
                ui.label(
                    egui::RichText::new("Target height")
                        .small()
                        .color(theme::TEXT_DIM),
                );
                ui.add(
                    egui::DragValue::new(&mut sculpt.target_height)
                        .speed(0.1)
                        .range(-MAX_SCULPT_DISTANCE..=MAX_SCULPT_DISTANCE),
                );
            });
        }
        SculptOpKind::Raise | SculptOpKind::Lower => {
            ui.horizontal(|ui| {
                ui.label(egui::RichText::new("Delta").small().color(theme::TEXT_DIM));
                ui.add(
                    egui::DragValue::new(&mut sculpt.delta)
                        .speed(0.1)
                        .range(-MAX_SCULPT_DISTANCE..=MAX_SCULPT_DISTANCE),
                );
            });
        }
        SculptOpKind::Smooth => {
            ui.label(
                egui::RichText::new("Strength controls the pull toward the region mean.")
                    .small()
                    .color(theme::TEXT_MUTED),
            );
        }
    }
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("Material")
                .small()
                .color(theme::TEXT_DIM),
        );
        ui.add(egui::TextEdit::singleline(&mut sculpt.material).desired_width(120.0));
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_real_scale_rejects_non_positive_and_non_finite() {
        assert!(has_real_scale(1.0));
        assert!(has_real_scale(0.0001));
        assert!(!has_real_scale(0.0));
        assert!(!has_real_scale(-1.0));
        assert!(!has_real_scale(f64::NAN));
        assert!(!has_real_scale(f64::INFINITY));
    }

    #[test]
    fn distance_unit_suffix_matches_scale_validity() {
        assert_eq!(distance_unit_suffix(1.0), " m");
        assert_eq!(distance_unit_suffix(0.001), " m");
        assert_eq!(distance_unit_suffix(0.0), " world units");
        assert_eq!(distance_unit_suffix(-1.0), " world units");
        assert_eq!(distance_unit_suffix(f64::NAN), " world units");
    }

    #[test]
    fn scale_chip_text_unset_matches_report_panel_wording_exactly() {
        // Byte-identical to `proposal_report_panel`'s NFR-4 chip
        // (`panels/proposal_report_panel.rs:279`) so the two surfaces never
        // say "no map scale" two different ways.
        assert_eq!(scale_chip_text(0.0), "no map scale — showing world units");
        assert_eq!(scale_chip_text(-5.0), "no map scale — showing world units");
        assert_eq!(
            scale_chip_text(f64::NAN),
            "no map scale — showing world units"
        );
    }

    #[test]
    fn scale_chip_text_known_scale_shows_the_value() {
        let text = scale_chip_text(2.5);
        assert!(
            text.contains("2.5000"),
            "expected formatted scale, got {text}"
        );
        assert!(!text.contains("no map scale"));
    }

    #[test]
    fn circle_footprint_has_expected_segment_count_and_radius() {
        let fp = circle_footprint(2.0);
        assert_eq!(fp.len(), FOOTPRINT_SEGMENTS);
        for [x, z] in fp {
            let r = (x * x + z * z).sqrt();
            assert!((r - 2.0).abs() < 1e-3, "point off-radius: {x},{z} -> {r}");
        }
    }

    #[test]
    fn rect_footprint_is_a_2r_side_square_matching_sculpt_footprint_area() {
        let fp = rect_footprint(3.0);
        assert_eq!(fp.len(), 4);
        let expected_area = sculpt_footprint_area(&SculptToolState {
            shape_mode: SculptShapeMode::Rect,
            radius: 3.0,
            ..Default::default()
        });
        // Shoelace of the emitted footprint must match the pure area formula
        // it is meant to back — same shape, two independent computations.
        let mut sum = 0.0f32;
        for i in 0..fp.len() {
            let [x1, z1] = fp[i];
            let [x2, z2] = fp[(i + 1) % fp.len()];
            sum += x1 * z2 - x2 * z1;
        }
        assert!((sum.abs() * 0.5 - expected_area).abs() < 1e-3);
    }

    #[test]
    fn sculpt_area_disc_rect_and_polygon() {
        // Circle: πr².
        let circle = SculptToolState {
            shape_mode: SculptShapeMode::Circle,
            radius: 2.0,
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&circle) - std::f32::consts::PI * 4.0).abs() < 1e-3);
        // Rect: a 2r-per-side square → (2r)².
        let rect = SculptToolState {
            shape_mode: SculptShapeMode::Rect,
            radius: 3.0,
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&rect) - 36.0).abs() < 1e-3);
        // Polygon: a 10×10 square draft → area 100; <3 points → 0.
        let poly = SculptToolState {
            shape_mode: SculptShapeMode::Polygon,
            region_draft: vec![[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0]],
            ..Default::default()
        };
        assert!((sculpt_footprint_area(&poly) - 100.0).abs() < 1e-3);
        let empty = SculptToolState {
            shape_mode: SculptShapeMode::Polygon,
            region_draft: vec![[0.0, 0.0], [1.0, 0.0]],
            ..Default::default()
        };
        assert_eq!(sculpt_footprint_area(&empty), 0.0);
    }

    #[test]
    fn sculpt_numeric_state_recovers_from_non_finite_values() {
        let mut state = SculptToolState {
            radius: f32::NAN,
            strength: f32::INFINITY,
            target_height: f32::NEG_INFINITY,
            delta: f32::NAN,
            ..Default::default()
        };
        state.sanitize_numeric_state();
        assert_eq!(state.radius, 5.0);
        assert_eq!(state.strength, 0.5);
        assert_eq!(state.target_height, 0.0);
        assert_eq!(state.delta, 1.0);
    }
}
