[package]
name = "fe-format"
version = "0.1.0"
edition = "2021"

[dependencies]
fe-runtime = { path = "../fe-runtime" }
serde = { workspace = true }
serde_json = { workspace = true }
zip = { version = "2", default-features = false, features = ["deflate"] }
anyhow = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = { workspace = true }
base64 = "0.22"
bs58 = "0.5"

[dev-dependencies]
rand = "0.8"
