use serde::{de::DeserializeOwned, Serialize};
use surrealdb::types::SurrealValue;

/// Type alias for the SurrealDB database handle used throughout the crate.
pub type Db = surrealdb::Surreal<surrealdb::engine::local::Db>;

/// Trait implemented by table-mapped structs (generated by [`define_table!`]).
///
/// Each implementor corresponds to exactly one SurrealDB table and carries
/// the DDL needed to define it, plus the name of the logical primary-key field.
pub trait Table: Serialize + DeserializeOwned + Send + Sync + 'static {
    /// SurrealDB table name (e.g. `"petal"`).
    const TABLE_NAME: &'static str;
    /// Name of the field that acts as the logical primary key (e.g. `"petal_id"`).
    const ID_FIELD: &'static str;
    /// Return the SurrealQL DDL that defines this table and all its fields.
    fn schema() -> String;
    /// Return the string value of the ID field on this instance.
    fn id_value(&self) -> String;
}

/// Generic repository providing typed CRUD over any [`Table`] implementor.
///
/// All methods are associated functions (no `&self`) — there is no instance
/// state.  For domain-specific queries (spatial lookups, full-text search,
/// SurrealQL `VERSION`, etc.) use [`Repo::query_raw`] or write free functions
/// that accept `&Db` and return `T`.
///
/// # Quick start
/// ```ignore
/// // Insert
/// Repo::<Petal>::create(&db, &petal).await?;
///
/// // Lookup
/// let p = Repo::<Petal>::find_by_id(&db, "01HZ…").await?;
///
/// // Partial update
/// Repo::<Petal>::merge_by_id(&db, "01HZ…", json!({"name": "new"})).await?;
/// ```
pub struct Repo<T: Table>(std::marker::PhantomData<T>);

impl<T: Table> Default for Repo<T> {
    fn default() -> Self {
        Self(std::marker::PhantomData)
    }
}

impl<T: Table> Repo<T> {
    pub fn new() -> Self {
        Self::default()
    }

    // ----- schema -----------------------------------------------------------

    /// Run this table's DDL (idempotent thanks to `IF NOT EXISTS`).
    pub async fn apply_schema(db: &Db) -> anyhow::Result<()> {
        db.query(T::schema()).await?.check()?;
        Ok(())
    }

    // ----- create -----------------------------------------------------------

    /// Insert a new row from a fully-populated struct.
    ///
    /// JSON `null` values are stripped before sending to SurrealDB because
    /// SurrealDB's `option<T>` type rejects `null` — it expects the field
    /// to be absent (interpreted as `NONE`) rather than explicitly null.
    pub async fn create(db: &Db, item: &T) -> anyhow::Result<()> {
        let val = strip_json_nulls(serde_json::to_value(item)?);
        let _: Option<serde_json::Value> = db
            .create(T::TABLE_NAME)
            .content(val)
            .await?;
        Ok(())
    }

    /// Insert a row from an arbitrary JSON value (useful when the struct
    /// doesn't perfectly match what SurrealDB expects, e.g. geometry casts).
    ///
    /// Null values are stripped — see [`create`] for rationale.
    pub async fn create_raw(db: &Db, content: serde_json::Value) -> anyhow::Result<()> {
        let _: Option<serde_json::Value> = db
            .create(T::TABLE_NAME)
            .content(strip_json_nulls(content))
            .await?;
        Ok(())
    }

    // ----- read -------------------------------------------------------------

    /// Find a single row by its logical ID field.
    pub async fn find_by_id(db: &Db, id: &str) -> anyhow::Result<Option<T>> {
        let sql = format!(
            "SELECT * FROM {} WHERE {} = $id LIMIT 1",
            T::TABLE_NAME,
            T::ID_FIELD,
        );
        let mut res: surrealdb::IndexedResults =
            db.query(&sql).bind(("id", id.to_string())).await?;
        let row: Option<serde_json::Value> = res.take(0)?;
        row.map(|v| serde_json::from_value(v))
            .transpose()
            .map_err(Into::into)
    }

    /// Return every row in the table.
    pub async fn find_all(db: &Db) -> anyhow::Result<Vec<T>> {
        let mut res: surrealdb::IndexedResults =
            db.query(format!("SELECT * FROM {}", T::TABLE_NAME)).await?;
        let rows: Vec<serde_json::Value> = res.take(0)?;
        rows.into_iter()
            .map(|v| serde_json::from_value(v).map_err(Into::into))
            .collect()
    }

    /// Return rows where `field == value`.
    ///
    /// `field` must be a safe SurrealQL identifier.
    pub async fn find_where(
        db: &Db,
        field: &str,
        value: impl Serialize + Send,
    ) -> anyhow::Result<Vec<T>> {
        if !is_safe_identifier(field) {
            anyhow::bail!("invalid field name: {field}");
        }
        let sql = format!("SELECT * FROM {} WHERE {} = $val", T::TABLE_NAME, field);
        let mut res: surrealdb::IndexedResults = db
            .query(&sql)
            .bind(("val", serde_json::to_value(value)?))
            .await?;
        let rows: Vec<serde_json::Value> = res.take(0)?;
        rows.into_iter()
            .map(|v| serde_json::from_value(v).map_err(Into::into))
            .collect()
    }

    // ----- update -----------------------------------------------------------

    /// Partial update via SurrealQL `UPDATE … MERGE`.
    ///
    /// Only the fields present in `updates` are written; the rest are left
    /// untouched.  `updates` must serialise to a JSON object.
    pub async fn merge_by_id(
        db: &Db,
        id: &str,
        updates: impl Serialize + Send,
    ) -> anyhow::Result<()> {
        let sql = format!(
            "UPDATE {} MERGE $data WHERE {} = $id",
            T::TABLE_NAME,
            T::ID_FIELD,
        );
        db.query(&sql)
            .bind(("data", serde_json::to_value(updates)?))
            .bind(("id", id.to_string()))
            .await?;
        Ok(())
    }

    // ----- delete -----------------------------------------------------------

    /// Delete all rows from the table.
    pub async fn delete_all(db: &Db) -> anyhow::Result<()> {
        db.query(format!("DELETE FROM {}", T::TABLE_NAME)).await?;
        Ok(())
    }

    /// Delete rows where the ID field matches.
    pub async fn delete_by_id(db: &Db, id: &str) -> anyhow::Result<()> {
        let sql = format!(
            "DELETE FROM {} WHERE {} = $id",
            T::TABLE_NAME,
            T::ID_FIELD,
        );
        db.query(&sql).bind(("id", id.to_string())).await?;
        Ok(())
    }

    // ----- aggregate --------------------------------------------------------

    /// Count rows in the table.
    pub async fn count(db: &Db) -> anyhow::Result<u64> {
        let mut res: surrealdb::IndexedResults = db
            .query(format!(
                "SELECT count() FROM {} GROUP ALL",
                T::TABLE_NAME,
            ))
            .await?;
        let rows: Vec<serde_json::Value> = res.take(0)?;
        Ok(rows
            .first()
            .and_then(|v| v["count"].as_u64())
            .unwrap_or(0))
    }

    // ----- escape hatch -----------------------------------------------------

    /// Execute arbitrary SurrealQL and deserialise the first result set as `Vec<T>`.
    pub async fn query_raw(db: &Db, sql: &str) -> anyhow::Result<Vec<T>> {
        let mut res: surrealdb::IndexedResults = db.query(sql).await?;
        let rows: Vec<serde_json::Value> = res.take(0)?;
        rows.into_iter()
            .map(|v| serde_json::from_value(v).map_err(Into::into))
            .collect()
    }
}

/// Remove keys whose value is `null` from a JSON object (top-level only).
///
/// SurrealDB's `option<T>` fields reject JSON `null` — the field must be
/// absent for SurrealDB to treat it as `NONE`. This helper strips those
/// nulls so Rust `Option::None` values round-trip correctly.
pub(crate) fn strip_json_nulls(val: serde_json::Value) -> serde_json::Value {
    match val {
        serde_json::Value::Object(map) => {
            serde_json::Value::Object(map.into_iter().filter(|(_, v)| !v.is_null()).collect())
        }
        other => other,
    }
}

/// Validate that `s` is a safe SurrealQL field identifier.
fn is_safe_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        None => false,
        Some(first) => {
            (first.is_ascii_alphabetic() || first == '_')
                && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn safe_identifiers() {
        assert!(is_safe_identifier("petal_id"));
        assert!(is_safe_identifier("name"));
        assert!(is_safe_identifier("_private"));
        assert!(!is_safe_identifier(""));
        assert!(!is_safe_identifier("1bad"));
        assert!(!is_safe_identifier("no spaces"));
        assert!(!is_safe_identifier("drop;--"));
    }

    // --- strip_json_nulls ---

    #[test]
    fn strip_nulls_removes_null_fields() {
        let input = serde_json::json!({
            "name": "hello",
            "namespace_id": null,
            "created_at": "2026-01-01",
        });
        let result = strip_json_nulls(input);
        let obj = result.as_object().unwrap();
        assert_eq!(obj.len(), 2);
        assert_eq!(obj["name"], "hello");
        assert_eq!(obj["created_at"], "2026-01-01");
        assert!(!obj.contains_key("namespace_id"));
    }

    #[test]
    fn strip_nulls_preserves_non_null_options() {
        let input = serde_json::json!({
            "name": "verse",
            "namespace_id": "abc123",
        });
        let result = strip_json_nulls(input);
        let obj = result.as_object().unwrap();
        assert_eq!(obj.len(), 2);
        assert_eq!(obj["namespace_id"], "abc123");
    }

    #[test]
    fn strip_nulls_all_null_produces_empty_object() {
        let input = serde_json::json!({
            "a": null,
            "b": null,
        });
        let result = strip_json_nulls(input);
        assert_eq!(result, serde_json::json!({}));
    }

    #[test]
    fn strip_nulls_no_nulls_is_identity() {
        let input = serde_json::json!({
            "x": 42,
            "y": "hello",
            "z": [1, 2, 3],
        });
        let result = strip_json_nulls(input.clone());
        assert_eq!(result, input);
    }

    #[test]
    fn strip_nulls_non_object_passthrough() {
        // Non-object values should pass through unchanged.
        assert_eq!(strip_json_nulls(serde_json::json!(42)), serde_json::json!(42));
        assert_eq!(strip_json_nulls(serde_json::json!("str")), serde_json::json!("str"));
        assert_eq!(strip_json_nulls(serde_json::json!(null)), serde_json::json!(null));
        assert_eq!(strip_json_nulls(serde_json::json!([1, null, 3])), serde_json::json!([1, null, 3]));
    }

    #[test]
    fn strip_nulls_preserves_nested_nulls() {
        // Only top-level nulls are stripped; nested objects keep their nulls
        // because SurrealDB FLEXIBLE fields may legitimately contain them.
        let input = serde_json::json!({
            "name": "test",
            "metadata": {"inner": null},
            "removed": null,
        });
        let result = strip_json_nulls(input);
        let obj = result.as_object().unwrap();
        assert_eq!(obj.len(), 2);
        assert!(obj.contains_key("metadata"));
        assert!(obj["metadata"]["inner"].is_null());
    }
}
